version: '3'

services:
  # mongo:
  #   image: mongo
  #   container_name: mongo
  #   ports:
  #     - 27017:27017
  
  backend:
    build: .
    container_name: backend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/user/backend
    # links:
    #   - mongo
    # depends_on:
    #   - mongo

networks:
  default:
    name: backend_default